import { useState } from "react";
import { Link } from "react-router";

interface ReportTemplate {
  id: string;
  name: string;
  type: string;
  schedule: string;
  lastRun: string;
  nextRun: string;
  status: "completed" | "scheduled" | "failed" | "running";
  recipients: number;
  format: string;
}

const MOCK_REPORTS: ReportTemplate[] = [
  {
    id: "r1",
    name: "Monthly HIPAA Compliance Summary",
    type: "Compliance",
    schedule: "1st of each month",
    lastRun: "Feb 1, 2026",
    nextRun: "Mar 1, 2026",
    status: "completed",
    recipients: 8,
    format: "PDF",
  },
  {
    id: "r2",
    name: "Weekly SLA Performance Report",
    type: "Performance",
    schedule: "Every Monday 8:00 AM",
    lastRun: "Feb 23, 2026",
    nextRun: "Mar 2, 2026",
    status: "completed",
    recipients: 12,
    format: "PDF",
  },
  {
    id: "r3",
    name: "Credential Expiration Alert Digest",
    type: "Credentialing",
    schedule: "Daily 6:00 AM",
    lastRun: "Feb 28, 2026",
    nextRun: "Mar 1, 2026",
    status: "running",
    recipients: 5,
    format: "Email",
  },
  {
    id: "r4",
    name: "Quarterly Incident Trend Analysis",
    type: "Safety",
    schedule: "Quarterly",
    lastRun: "Jan 1, 2026",
    nextRun: "Apr 1, 2026",
    status: "completed",
    recipients: 15,
    format: "XLSX",
  },
  {
    id: "r5",
    name: "Training Compliance Gap Report",
    type: "Training",
    schedule: "Bi-weekly",
    lastRun: "Feb 17, 2026",
    nextRun: "Mar 3, 2026",
    status: "scheduled",
    recipients: 6,
    format: "PDF",
  },
  {
    id: "r6",
    name: "PHI Access Anomaly Report",
    type: "Privacy",
    schedule: "Daily 7:00 AM",
    lastRun: "Feb 27, 2026",
    nextRun: "Mar 1, 2026",
    status: "failed",
    recipients: 3,
    format: "PDF",
  },
];

const RECENT_ACTIVITY = [
  { action: "Generated", report: "Weekly SLA Performance Report", time: "2 hours ago", icon: "ti-file-check", color: "success" },
  { action: "Distributed", report: "HIPAA Compliance Summary", time: "1 day ago", icon: "ti-send", color: "primary" },
  { action: "Failed", report: "PHI Access Anomaly Report", time: "1 day ago", icon: "ti-alert-triangle", color: "danger" },
  { action: "Scheduled", report: "Training Compliance Gap Report", time: "3 days ago", icon: "ti-clock", color: "warning" },
];

function getStatusBadge(status: ReportTemplate["status"]) {
  const map = {
    completed: "badge-soft-success border border-success text-success",
    scheduled: "badge-soft-primary border border-primary text-primary",
    running: "badge-soft-warning border border-warning text-warning",
    failed: "badge-soft-danger border border-danger text-danger",
  };
  const labels = { completed: "Completed", scheduled: "Scheduled", running: "Running", failed: "Failed" };
  return { cls: map[status], label: labels[status] };
}

function getFormatIcon(format: string) {
  if (format === "PDF") return "ti-file-type-pdf text-danger";
  if (format === "XLSX") return "ti-file-spreadsheet text-success";
  return "ti-mail text-primary";
}

const AutoGeneratedReports = () => {
  const [activeTab, setActiveTab] = useState<"templates" | "activity">("templates");

  return (
    <div className="card shadow-sm flex-fill w-100">
      <div className="card-header d-flex align-items-center justify-content-between">
        <div className="d-flex align-items-center gap-2">
          <h5 className="fw-bold mb-0">Auto-Generated Reports</h5>
          <span className="badge bg-primary rounded-pill">{MOCK_REPORTS.length}</span>
        </div>
        <button className="btn btn-sm btn-primary d-inline-flex align-items-center gap-1">
          <i className="ti ti-plus fs-14" /> New Report
        </button>
      </div>
      <div className="card-body p-0">
        {/* Tabs */}
        <ul className="nav nav-tabs nav-tabs-solid nav-justified px-3 pt-3">
          <li className="nav-item">
            <Link
              to="#"
              className={`nav-link ${activeTab === "templates" ? "active" : ""}`}
              onClick={(e) => { e.preventDefault(); setActiveTab("templates"); }}
            >
              <i className="ti ti-template me-1" /> Templates
            </Link>
          </li>
          <li className="nav-item">
            <Link
              to="#"
              className={`nav-link ${activeTab === "activity" ? "active" : ""}`}
              onClick={(e) => { e.preventDefault(); setActiveTab("activity"); }}
            >
              <i className="ti ti-activity me-1" /> Recent Activity
            </Link>
          </li>
        </ul>

        {activeTab === "templates" && (
          <div className="table-responsive" style={{ maxHeight: 360, overflowY: "auto" }}>
            <table className="table table-sm mb-0">
              <thead className="thead-light" style={{ position: "sticky", top: 0, zIndex: 1 }}>
                <tr>
                  <th>Report</th>
                  <th className="text-center">Schedule</th>
                  <th className="text-center">Format</th>
                  <th className="text-center">Status</th>
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {MOCK_REPORTS.map((r) => {
                  const st = getStatusBadge(r.status);
                  return (
                    <tr key={r.id}>
                      <td>
                        <div>
                          <span className="fw-medium">{r.name}</span>
                          <br />
                          <small className="text-muted">
                            <i className="ti ti-users fs-11 me-1" />
                            {r.recipients} recipients &middot; Next: {r.nextRun}
                          </small>
                        </div>
                      </td>
                      <td className="text-center align-middle">
                        <small>{r.schedule}</small>
                      </td>
                      <td className="text-center align-middle">
                        <i className={`ti ${getFormatIcon(r.format)} fs-16`} title={r.format} />
                      </td>
                      <td className="text-center align-middle">
                        <span className={`badge fs-11 py-1 rounded fw-medium ${st.cls}`}>{st.label}</span>
                      </td>
                      <td className="text-end align-middle">
                        <div className="d-flex justify-content-end gap-1">
                          <button className="btn btn-sm btn-outline-white px-2" title="Run Now">
                            <i className="ti ti-player-play fs-14" />
                          </button>
                          <button className="btn btn-sm btn-outline-white px-2" title="Download Last">
                            <i className="ti ti-download fs-14" />
                          </button>
                          <button className="btn btn-sm btn-outline-white px-2" title="Settings">
                            <i className="ti ti-settings fs-14" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {activeTab === "activity" && (
          <div className="px-3 pb-3" style={{ maxHeight: 360, overflowY: "auto" }}>
            {RECENT_ACTIVITY.map((a, i) => (
              <div key={i} className={`d-flex align-items-start gap-3 py-3 ${i < RECENT_ACTIVITY.length - 1 ? "border-bottom" : ""}`}>
                <div
                  className={`d-flex align-items-center justify-content-center rounded-circle bg-${a.color}-transparent flex-shrink-0`}
                  style={{ width: 36, height: 36 }}
                >
                  <i className={`ti ${a.icon} text-${a.color} fs-16`} />
                </div>
                <div className="flex-fill min-w-0">
                  <p className="mb-0 fw-medium fs-13">
                    <span className={`text-${a.color}`}>{a.action}</span>{" "}
                    <span className="text-truncate">{a.report}</span>
                  </p>
                  <small className="text-muted">{a.time}</small>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default AutoGeneratedReports;
