import PageHeader from "../../../../../core/common/page-header/PageHeader";
import SLAComplianceTracker from "./widgets/SLAComplianceTracker";
import AutoGeneratedReports from "./widgets/AutoGeneratedReports";
import DemandForecasting from "./widgets/DemandForecasting";
import AuditTrailBrowser from "./widgets/AuditTrailBrowser";
import HIPAAAccessMonitor from "./widgets/HIPAAAccessMonitor";
import CredentialTracker from "./widgets/CredentialTracker";
import TrainingComplianceMatrix from "./widgets/TrainingComplianceMatrix";
import IncidentReportingDashboard from "./widgets/IncidentReportingDashboard";

const ComplianceDashboard = () => {
  return (
    <>
      <div className="page-wrapper">
        <div className="content pb-0">
          <PageHeader title="Compliance Dashboard" />

          {/* Row 1: SLA Tracker + Auto Reports */}
          <div className="row mb-4 g-3 g-lg-4">
            <div className="col-12 col-xl-6 d-flex">
              <SLAComplianceTracker />
            </div>
            <div className="col-12 col-xl-6 d-flex">
              <AutoGeneratedReports />
            </div>
          </div>

          {/* Row 2: Demand Forecasting + Audit Trail */}
          <div className="row mb-4 g-3 g-lg-4">
            <div className="col-12 col-xl-6 d-flex">
              <DemandForecasting />
            </div>
            <div className="col-12 col-xl-6 d-flex">
              <AuditTrailBrowser />
            </div>
          </div>

          {/* Row 3: HIPAA Monitor + Credential Tracker */}
          <div className="row mb-4 g-3 g-lg-4">
            <div className="col-12 col-xl-6 d-flex">
              <HIPAAAccessMonitor />
            </div>
            <div className="col-12 col-xl-6 d-flex">
              <CredentialTracker />
            </div>
          </div>

          {/* Row 4: Training Matrix (full width) */}
          <div className="row mb-4 g-3 g-lg-4">
            <div className="col-12 d-flex">
              <TrainingComplianceMatrix />
            </div>
          </div>

          {/* Row 5: Incident Reporting (full width) */}
          <div className="row mb-4 g-3 g-lg-4">
            <div className="col-12 d-flex">
              <IncidentReportingDashboard />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ComplianceDashboard;
