import { useState, useCallback } from "react";
import PageHeader from "../../../../../core/common/page-header/PageHeader";
import SLAComplianceTracker from "./widgets/SLAComplianceTracker";
import AutoGeneratedReports from "./widgets/AutoGeneratedReports";
import DemandForecasting from "./widgets/DemandForecasting";
import AuditTrailBrowser from "./widgets/AuditTrailBrowser";
import HIPAAAccessMonitor from "./widgets/HIPAAAccessMonitor";
import CredentialTracker from "./widgets/CredentialTracker";
import TrainingComplianceMatrix from "./widgets/TrainingComplianceMatrix";
import IncidentReportingDashboard from "./widgets/IncidentReportingDashboard";

// Attention items pulled from widget data for the top-level summary
const ATTENTION_ITEMS = [
  { label: "HIPAA violations", count: 1, severity: "critical" as const, section: "compliance", icon: "ti-shield-lock" },
  { label: "credentials expiring this week", count: 2, severity: "critical" as const, section: "credentials", icon: "ti-certificate" },
  { label: "overdue trainings", count: 20, severity: "warning" as const, section: "training", icon: "ti-school" },
  { label: "sentinel event open", count: 1, severity: "critical" as const, section: "incidents", icon: "ti-urgent" },
];

// Section definitions for navigation and grouping
const SECTIONS = [
  { id: "compliance", label: "Compliance & Reporting", icon: "ti-chart-pie" },
  { id: "operations", label: "Operations & Auditing", icon: "ti-settings" },
  { id: "credentials", label: "Credentials & HIPAA", icon: "ti-shield-check" },
  { id: "training", label: "Training", icon: "ti-school" },
  { id: "incidents", label: "Incidents", icon: "ti-alert-triangle" },
] as const;

const ComplianceDashboard = () => {
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});

  const toggleSection = useCallback((id: string) => {
    setCollapsed((prev) => ({ ...prev, [id]: !prev[id] }));
  }, []);

  const scrollToSection = useCallback((id: string) => {
    const el = document.getElementById(`section-${id}`);
    if (el) {
      // Uncollapse if collapsed
      setCollapsed((prev) => ({ ...prev, [id]: false }));
      setTimeout(() => el.scrollIntoView({ behavior: "smooth", block: "start" }), 50);
    }
  }, []);

  const criticalItems = ATTENTION_ITEMS.filter((i) => i.severity === "critical");
  const warningItems = ATTENTION_ITEMS.filter((i) => i.severity === "warning");

  return (
    <>
      <div className="page-wrapper">
        <div className="content pb-0">
          <PageHeader title="Compliance Dashboard" />

          {/* ── Attention Needed Banner ── */}
          <div
            className="card mb-4 border-0"
            style={{ background: "linear-gradient(135deg, #FEF2F2 0%, #FFF7ED 50%, #FFFBEB 100%)" }}
            role="alert"
            aria-label="Items requiring immediate attention"
          >
            <div className="card-body py-3">
              <div className="d-flex align-items-center mb-2">
                <i className="ti ti-alert-circle text-danger fs-20 me-2" />
                <h6 className="fw-bold mb-0 fs-15">Attention Needed</h6>
                <span className="badge bg-danger rounded-pill ms-2">
                  {ATTENTION_ITEMS.reduce((s, i) => s + i.count, 0)} items
                </span>
              </div>
              <div className="d-flex flex-wrap gap-3">
                {criticalItems.map((item) => (
                  <button
                    key={item.label}
                    className="btn btn-sm btn-outline-danger d-inline-flex align-items-center gap-1 bg-white"
                    onClick={() => scrollToSection(item.section)}
                    style={{ minHeight: 36 }}
                  >
                    <i className={`ti ${item.icon} fs-14`} />
                    <span className="fw-bold">{item.count}</span> {item.label}
                  </button>
                ))}
                {warningItems.map((item) => (
                  <button
                    key={item.label}
                    className="btn btn-sm btn-outline-warning d-inline-flex align-items-center gap-1 bg-white"
                    onClick={() => scrollToSection(item.section)}
                    style={{ minHeight: 36 }}
                  >
                    <i className={`ti ${item.icon} fs-14`} />
                    <span className="fw-bold">{item.count}</span> {item.label}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* ── Section Jump Navigation ── */}
          <div className="d-flex align-items-center gap-2 mb-4 flex-wrap">
            <span className="fs-12 text-muted fw-medium me-1">Jump to:</span>
            {SECTIONS.map((s) => (
              <button
                key={s.id}
                className="btn btn-sm btn-outline-white bg-white d-inline-flex align-items-center gap-1 shadow-sm"
                onClick={() => scrollToSection(s.id)}
                style={{ minHeight: 36 }}
              >
                <i className={`ti ${s.icon} fs-14`} />
                {s.label}
              </button>
            ))}
          </div>

          {/* ── Section: Compliance & Reporting ── */}
          <div id="section-compliance" className="mb-2" style={{ scrollMarginTop: 80 }}>
            <SectionHeader
              icon="ti-chart-pie"
              iconColor="text-primary"
              title="Compliance & Reporting"
              collapsed={collapsed["compliance"]}
              onToggle={() => toggleSection("compliance")}
            />
            {!collapsed["compliance"] && (
              <div className="row mb-4 g-3 g-lg-4">
                <div className="col-12 col-xl-6 d-flex">
                  <SLAComplianceTracker />
                </div>
                <div className="col-12 col-xl-6 d-flex">
                  <AutoGeneratedReports />
                </div>
              </div>
            )}
          </div>

          {/* ── Section: Operations & Auditing ── */}
          <div id="section-operations" className="mb-2" style={{ scrollMarginTop: 80 }}>
            <SectionHeader
              icon="ti-settings"
              iconColor="text-info"
              title="Operations & Auditing"
              collapsed={collapsed["operations"]}
              onToggle={() => toggleSection("operations")}
            />
            {!collapsed["operations"] && (
              <div className="row mb-4 g-3 g-lg-4">
                <div className="col-12 col-xl-6 d-flex">
                  <DemandForecasting />
                </div>
                <div className="col-12 col-xl-6 d-flex">
                  <AuditTrailBrowser />
                </div>
              </div>
            )}
          </div>

          {/* ── Section: Credentials & HIPAA ── */}
          <div id="section-credentials" className="mb-2" style={{ scrollMarginTop: 80 }}>
            <SectionHeader
              icon="ti-shield-check"
              iconColor="text-danger"
              title="Credentials & HIPAA"
              collapsed={collapsed["credentials"]}
              onToggle={() => toggleSection("credentials")}
            />
            {!collapsed["credentials"] && (
              <div className="row mb-4 g-3 g-lg-4">
                <div className="col-12 col-xl-6 d-flex">
                  <HIPAAAccessMonitor />
                </div>
                <div className="col-12 col-xl-6 d-flex">
                  <CredentialTracker />
                </div>
              </div>
            )}
          </div>

          {/* ── Section: Training ── */}
          <div id="section-training" className="mb-2" style={{ scrollMarginTop: 80 }}>
            <SectionHeader
              icon="ti-school"
              iconColor="text-warning"
              title="Training Compliance"
              collapsed={collapsed["training"]}
              onToggle={() => toggleSection("training")}
            />
            {!collapsed["training"] && (
              <div className="row mb-4 g-3 g-lg-4">
                <div className="col-12 d-flex">
                  <TrainingComplianceMatrix />
                </div>
              </div>
            )}
          </div>

          {/* ── Section: Incidents ── */}
          <div id="section-incidents" className="mb-4" style={{ scrollMarginTop: 80 }}>
            <SectionHeader
              icon="ti-alert-triangle"
              iconColor="text-danger"
              title="Incident & Event Reporting"
              collapsed={collapsed["incidents"]}
              onToggle={() => toggleSection("incidents")}
            />
            {!collapsed["incidents"] && (
              <div className="row mb-4 g-3 g-lg-4">
                <div className="col-12 d-flex">
                  <IncidentReportingDashboard />
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

/** Reusable section header with collapse toggle */
const SectionHeader = ({
  icon,
  iconColor,
  title,
  collapsed,
  onToggle,
}: {
  icon: string;
  iconColor: string;
  title: string;
  collapsed?: boolean;
  onToggle: () => void;
}) => (
  <div className="d-flex align-items-center justify-content-between mb-3 mt-2">
    <div className="d-flex align-items-center">
      <i className={`ti ${icon} ${iconColor} me-2 fs-20`} />
      <h5 className="fw-bold mb-0 fs-16">{title}</h5>
    </div>
    <button
      className="btn btn-sm btn-outline-white d-inline-flex align-items-center gap-1"
      onClick={onToggle}
      aria-expanded={!collapsed}
      aria-label={`${collapsed ? "Expand" : "Collapse"} ${title} section`}
      style={{ minHeight: 36 }}
    >
      <i className={`ti ti-chevron-${collapsed ? "down" : "up"} fs-14`} />
      <span className="fs-12">{collapsed ? "Expand" : "Collapse"}</span>
    </button>
  </div>
);

export default ComplianceDashboard;
